addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.16")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"        % "1.6.1")
addSbtPlugin("com.github.mwz"            % "sbt-sonar"            % "2.2.0")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "0.14.5")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.10.0-RC1")
//addSbtPlugin("com.sksamuel.scapegoat" % "sbt-scapegoat" % "1.4.7")
//addSbtPlugin("dev.zio"                % "zio-shield"    % "0.1.0")
